files:
  root_path: ../ILDCaloSim
  train_noisy: e-_Jun3/test/showers-10kE10GeV-RC10-1.hdf5
  train_sharp: e-_Jun3/test/showers-10kE10GeV-RC01-1.hdf5
params:
  epoch_count: 200
  weight_decay: 0.001
  kernel_size: 3
  hidden_count: 9
  learning_rate: 0.001
